### ISSUE TITLE
Fix Old Messages not working

### ISSUE THREAD

**Issue by scarlion1** [mattprecious/smstimefix#35]
i am on Sprint with a Galaxy S5 with stock 4.4.2 firmware and using SMS Time Fix 2.4.4.  All of my MMS messages that i receive are timestamped 27 hours in the past.  so i am trying to use the "Fix old messages" function but not having any luck.  e.g. suppose i receive an MMS and the time is Jun 20, 9:00 AM.  the MMS will get dated Jun 19, 6:00 AM.  i try to set the Starting date to Jun 20, 8:59AM and Ending date to Jun 20, 9:01AM, add 27 hours, MMS.... 0 messages were updated.  i also try Starting date of Jun 19, 5:59AM and ending date Jun 19, 6:01AM but still "0 messages were updated"

**Comment by mattprecious** [comment]
The Android 4.4 update basically killed the app. Pretty sure I'm not able to modify SMS messages unless the app is registered as the default SMS app for the phone (which is definitely not going to happen).

**Comment by scarlion1** [comment]
why is that definitely not going to happen?  there is a setting to change the default messaging app.  right now i can chose between the Samsung app and Titanium Backup... so shouldn't there be a way to register SMS Timefix as a messaging app so we can temporarily accomplish this time fix?

**Comment by mattprecious** [comment]
The main purpose of SMS Time Fix was to continuously adjust new messages as they arrive. The batch adjusting of old messages was supposed to be a one-time thing that new users do when they first install the app. The implementation is poor and the design is terrible (note that this app is over 5 years old at this point and hasn't been updated in 3 years).

I'd much rather write a whole new app specifically for that purpose instead of trying to shove support into this one. However, I don't really have the time or the motivation to start another app right now and I'm sure there's already plenty of other apps in the Play Store that are better suited for this task.
